// candidateService.js
const pool = require("../config/db"); // pg pool


async function addCandidateData(req, res) {
  try {
    const {
      user_id,
      sector,
      title,
      location,
      project_desc,
      reqn_quali,
      engineering,
      csit,
      commerce,
      mgmt,
      AnH,
      Science,
      Economics,
      Law,
      Medicine,
      Pharmacy,
      Architecture,
      Agri,
      SSc,
      Journalism,
      Design,
      Other,
      java_script,
      python,
      java,
      nodejs,
      react,
      sql,
      git,
      Machine_Learning,
      Data_Analytics,
      Excel,
      PowerBI,
      Tableau,
      Figma,
      Adobe_Creative_Suite,
      AutoCAD,
      MATLAB,
      Communication,
      Leadership,
      Problem_Solving,
      Team_Work,
      Project_Mgmt,
      Time_Mgmt,
      Critical_Thinking,
      Adaptability,
      Public_Speaking,
      Analytical_Thinking,
      SC,
      ST,
      OBC,
      EWS,
      PwD,
      WmnCandidates,
      FirstGenGrads,
      RuralBGCandidates,
      T2T3Res,
      FirstTimeIntPref
    } = req.body;
    const query = `
      INSERT INTO candidate_evaluation (
        user_id,
        sector,
        title,
        location,
        project_desc,
        reqn_quali,
        engineering,
        csit,
        commerce,
        mgmt,
        AnH,
        Science,
        Economics,
        Law,
        Medicine,
        Pharmacy,
        Architecture,
        Agri,
        SSc,
        Journalism,
        Design,
        Other,
        java_script,
        python,
        java,
        nodejs,
        react,
        sql,
        git,
        Machine_Learning,
        Data_Analytics,
        Excel,
        PowerBI,
        Tableau,
        Figma,
        Adobe_Creative_Suite,
        AutoCAD,
        MATLAB,
        Communication,
        Leadership,
        Problem_Solving,
        Team_Work,
        Project_Mgmt,
        Time_Mgmt,
        Critical_Thinking,
        Adaptability,
        Public_Speaking,
        Analytical_Thinking,
        SC,
        ST,
        OBC,
        EWS,
        PwD,
        WmnCandidates,
        FirstGenGrads,
        RuralBGCandidates,
        T2T3Res,
        FirstTimeIntPref)
        VALUES ($1, $2, $3, $4, $5, $6,
        COALESCE($7, false),
        COALESCE($8, false),
        COALESCE($9, false),
        COALESCE($10, false),
        COALESCE($11, false),
        COALESCE($12, false),
        COALESCE($13, false), 
        COALESCE($14, false), 
        COALESCE($15, false), 
        COALESCE($16, false), 
        COALESCE($17, false), 
        COALESCE($18, false), 
        COALESCE($19, false), 
        COALESCE($20, false),
        COALESCE($21, false), 
        COALESCE($22, false), 
        COALESCE($23, false), 
        COALESCE($24, false), 
        COALESCE($25, false), 
        COALESCE($26, false), 
        COALESCE($27, false), 
        COALESCE($28, false), 
        COALESCE($29, false), 
        COALESCE($30, false), 
        COALESCE($31, false), 
        COALESCE($32, false), 
        COALESCE($33, false), 
        COALESCE($34, false),
        COALESCE($35, false), 
        COALESCE($36, false), 
        COALESCE($37, false), 
        COALESCE($38, false), 
        COALESCE($39, false), 
        COALESCE($40, false), 
        COALESCE($41, false), 
        COALESCE($42, false), 
        COALESCE($43, false), 
        COALESCE($44, false),
        COALESCE($45, false),
        COALESCE($46, false),
        COALESCE($47, false),
        COALESCE($48, false),
        COALESCE($49, false),
        COALESCE($50, false),
        COALESCE($51, false),
        COALESCE($52, false),
        COALESCE($53, false),
        COALESCE($54, false),
        COALESCE($55, false),
        COALESCE($56, false),
        COALESCE($57, false)
      ) RETURNING *;
    `;

    const values = [
      user_id, sector, title, location, project_desc, reqn_quali,
      engineering,
      csit,
      commerce,
      mgmt,
      AnH,
      Science,
      Economics,
      Law,
      Medicine,
      Pharmacy,
      Architecture,
      Agri, 
      SSc,
      Journalism,
      Design,
      Other,
      java_script,
      python,
      java,
      nodejs,
      react,
      sql,
      git,
      Machine_Learning,
      Data_Analytics,
      Excel,
      PowerBI,
      Tableau,
      Figma,
      Adobe_Creative_Suite,
      AutoCAD,
      MATLAB,
      Communication,
      Leadership,
      Problem_Solving,
      Team_Work,
      Project_Mgmt,
      Time_Mgmt,
      Critical_Thinking,
      Adaptability,
      Public_Speaking,
      Analytical_Thinking,
      SC,
      ST,
      OBC,
      EWS,
      PwD,
      WmnCandidates,
      FirstGenGrads,
      RuralBGCandidates,
      T2T3Res,
      FirstTimeIntPref
    ];

    const result = await pool.query(query, values);
    res.json(result.rows[0]);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Database insert failed" });
  }
}

module.exports = { addCandidateData };
